### ISSUE TITLE
Ошибка telethone

### ISSUE THREAD

**Issue by georgevp** [cdies/news_aggregator#3]
Здравствуйте.
Настроил всё как указано, в том числе, в предыдущих issues.
При запуске main.py выскакивает следующая ошибка:
2023-03-05 19:18:42,304 - newscrap - INFO
Start...
------------------------------
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    history = loop.run_until_complete(get_history(client, n_id,
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result()
  File "/home/user/news_scrap/microservice/utils.py", line 27, in get_history  messages = await client.get_messages(chat_id, amount_messages)
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/messages.py", line 586, in get_messages return await it.collect()
  File "/home/user/.local/lib/python3.8/site-packages/telethon/requestiter.py", line 113, in collect  async for message in self:
  File "/home/user/.local/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__  if await self._load_next_chunk():
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/messages.py", line 184, in _load_next_chunk r = await self.client(self.request)
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__ return await self._call(self._sender, request, ordered=ordered)
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/users.py", line 84, in _call result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)

**Comment by cdies** [comment]
Бот не может прочитать новости, он добавлен в ваш канал как администратор?

**Comment by cdies** [comment]
`telegram_parser.py` отдельно у вас работает? (Не забыли про `bot.session` и `gazp.session`?)

**Comment by georgevp** [comment]
работает. новый вариант ошибки.
2023-03-12 20:59:48,999 - newscrap - INFO
Start...
------------------------------
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    client = telegram_parser('newscrap', api_id, api_hash, telegram_channels, posted_q,
  File "/home/user/news_scrap/microservice/telegram_parser.py", line 17, in telegram_parser  client.start()
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/auth.py", line 134, in start else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete  return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/auth.py", line 141, in _start  await self.connect()
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 537, in connect
    self.session.auth_key = self._sender.auth_key
  File "/home/user/.local/lib/python3.8/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/home/user/.local/lib/python3.8/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
Task was destroyed but it is pending!
task: <Task pending name='Task-14' coro=<MTProtoSender._send_loop() running at /home/user/.local/lib/python3.8/site-packages/telethon/network/mtprotosender.py:458> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa374d01af0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-15' coro=<MTProtoSender._recv_loop() running at /home/user/.local/lib/python3.8/site-packages/telethon/network/mtprotosender.py:501> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa374d01b20>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-12' coro=<Connection._send_loop() running at /home/user/.local/lib/python3.8/site-packages/telethon/network/connection/connection.py:306> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa374d01820>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-13' coro=<Connection._recv_loop() running at /home/user/.local/lib/python3.8/site-packages/telethon/network/connection/connection.py:324> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa374d01970>()]>>

**Comment by cdies** [comment]
Что-то с аутентификацией, копайте в сторону работы с telethon, может туториал какой есть для начинающих на youtube, нужно посмотреть.

**Comment by Nachos25** [comment]
У меня похожая ошибка.
D:\python.exe C:/Users/Asus/PycharmProjects/Work/main.py 
Handling /start command
Unhandled exception on handle_admin_commands
Traceback (most recent call last):
  File "D:\lib\site-packages\telethon\client\updates.py", line 570, in _dispatch_update
    await callback(event)
  File "C:\Users\Asus\PycharmProjects\Work\main.py", line 88, in handle_admin_commands
    response = await client.get_messages(event.chat_id, limit=1)
  File "D:\lib\site-packages\telethon\client\messages.py", line 603, in get_messages
    return await it.collect()
  File "D:\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "D:\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "D:\lib\site-packages\telethon\client\messages.py", line 184, in _load_next_chunk
    r = await self.client(self.request)
  File "D:\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "D:\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)
Не знаю как ее решить. Буду благодарен за помощь. Если надо будет код могу скинуть.

**Comment by georgevp** [comment]
К сожалению пришлось использовать requests.

**Comment by Nachos25** [comment]
Сможешь помочь?

**Comment by Msakhibullin24** [comment]
Здравствуйте,Дорогой разработчик данного проекта.Подскажите пожалуйста что делать в такой ситуации??
![изображение](https://github.com/cdies/news_aggregator/assets/121098677/bbac6c7a-5dd8-466f-9f99-117ac7d502cf)
![изображение](https://github.com/cdies/news_aggregator/assets/121098677/946d228d-1500-45e2-86de-6b26f884d467)

**Comment by Msakhibullin24** [comment]
Вроде пофиксил но теперь 
![изображение](https://github.com/cdies/news_aggregator/assets/121098677/80e2ebcf-7a75-4bbd-9e44-301b9df6926a)
после данного соббщения не начинает бот парсить

буквально ничего не происходит подскажите в чем проблема?
